### ISSUE TITLE
Skip EmulationStation

### ISSUE THREAD

**Issue by tarvip** [shantigilbert/CoreELEC#11]
First, thank you for good work.

I wonder is there a way to go from Kodi directly to Retroarch and back and skip EmulationStation altogether?

I understand EmulationStation is more like a frontend for Retroarch, but I think Retroarch has good enough GUI.

**Comment by tarvip** [comment]
Nvm, created a small launcher app to launch retroarch directly from kodi.

**Comment by tarvip** [comment]
sure, uploaded zip can be found here: https://gofile.io/?c=WEdNDu

**Comment by shantigilbert** [comment]
Thank you!
