### ISSUE TITLE
Request release of Sx05RE plug-in installation video tutorial?

### ISSUE THREAD

**Issue by ji125443** [shantigilbert/CoreELEC#13]
On YouTube...

**Comment by shantigilbert** [comment]
There is not much to explain but I will try to do it here, I will list 2 ways to copy it to your box.

Method 1:

- Download the zip file that corresponds to your box (s905 or S912) with a computer
- Copy it to a USB stick and connect it to your box

Method 2

- Using a computer connected to the same network as your box
- Open network shares and select “Downloads”
- Copy the file

How to install

- Go into add-ons, install from zip file
- It will prompt to allow external sources, follow the instructions to do so
- Go back to add-ons, install from zip file
- Navigate to your USB stick or the downloads folder and select the add-on
- Wait 3 or so minutes
- Enjoy
