### ISSUE TITLE
External roms device format issue

### ISSUE THREAD

**Issue by wdmomoxx** [shantigilbert/CoreELEC#15]
I tested the S905 external roms, roms can be recognized under FAT/NTSF, but a type of simulator like GB/GBC/GBA can't enter the game.

**Comment by shantigilbert** [comment]
Sorry I don't understand the issue... 

can you SSH to your box and send me the sx05re.log?

**Comment by wdmomoxx** [comment]
Usb device is fat32 format
the sx05re.log is this.

```
Sx05RE Run Log
First parameter: GBC
Second Parameter: /storage/roms/gb/俄罗斯方块.zip
Run Command is:
/usr/bin/retroarch -L /tmp/cores/gambatte_libretro.so /storage/roms/gb/俄罗斯方块.zip
Emulator Output is:
Wrong data-format, corrupt or unsupported ROM.
```
If the usb device changes to ext4 format, it works fine.

Sorroy for my poor english.

**Comment by shantigilbert** [comment]
It seems to me to be a problem with the characters used "俄罗斯方块" I wonder what it gets converted too? do you have any ROM with English characters that you can use to test?

**Comment by wdmomoxx** [comment]
I found the problem, not the character. I will unpack the zip and put it into the fat32 device. The file name has not changed and it works fine. I don't understand why there is such a difference under fat32 and ext4.

**Comment by shantigilbert** [comment]
Sorry I have no idea, it is clearly a character problem, but since I don't use any of those characters, I can't reproduce nor know why its happening.  Feel free to reopen the issue if you find more information, but as for now I have no idea how to help
